### ISSUE TITLE
Bewegung der Spieler, bzw. Bewegung der Kamera

### ISSUE THREAD

**Issue by PinkFluffyUnicorn** [PinkFluffyUnicorn/WitchMaze#26]
Kamerabewegung, sollte nicht aus dem Prototypen übernommen werden oder nur für den Prototypen, da die blöd war ...

**Comment by PinkFluffyUnicorn** [comment]
Ist jetzt beim Player mit drin :)

**Comment by PinkFluffyUnicorn** [comment]
vertauscht -.- :D tastatursteuerung vorhanden, GamePadsteurung muss noch gemacht werden

**Comment by toschwar** [comment]
kann ich die machen?
