### ISSUE TITLE
Prototyp Modelle erzeugen

### ISSUE THREAD

**Issue by PinkFluffyUnicorn** [PinkFluffyUnicorn/WitchMaze#5]
Prototyp modelle für Labyrinth wand, boden und schwarzes Loch erzeugen 
Prototyp modelle für Spieler erzeugen

**Comment by toschwar** [comment]
als Spieler hab ich ein Würfel als Prototyp

**Comment by PinkFluffyUnicorn** [comment]
modelle für Boden, schwarzes Loch und wand sind schon drin, Item modell existiert auch schon
